<h1>Awesome Pagination</h1>

<p>I could if you hadn't turned on the light and shut off my stereo. Then we'll go with that data file! You guys go on without me! I'm going to go... look for more stuff to steal! What are you hacking off? Is it my torso?! 'It is!' My precious torso! You know, I was God once. I found what I need. And it's not friends, it's things.</p>
<p>No argument here. Negative, bossy meat creature! Look, last night was a mistake. Of all the friends I've had... you're the first.</p>
<p>Fry! Stay back! He's too powerful! They're like sex, except I'm having them! Does anybody else feel jealous and aroused and worried? You wouldn't. Ask anyway! We don't have a brig.</p>

<div class="paged-data-container">
    <?php echo $this->render('index/index.ajax.phtml') ?>
</div>