<?php if ($this->pageCount > 0) : ?>
<div class="paginator-pages">
    <p>Pages:</p>
    <ol>
        <?php foreach ($this->pagesInRange as $page) : ?>
        <li>
            <?php if ($page == $this->current) : ?>
            <span><?php echo $page ?></span>
            <?php else : ?>
            <a title="Page <?php echo $page ?>" href="<?php echo $this->url(array(
                'page' => $page
            )) ?>"><?php echo $page ?></a>
            <?php endif ?>
        </li>
        <?php endforeach ?>
    </ol>
</div>
<div class="paginator-nav">
    <ul>
        <li>
            <?php if (isset($this->previous)) : ?>
            <a title="Previous" class="paginator-prev" href="<?php echo $this->url(array(
                'page' => $this->previous
            )) ?>">Previous</a>
            <?php else : ?>
            <span class="paginator-prev">Previous</span>
            <?php endif ?>
        </li>
        <li>
            <?php if (isset($this->next)) : ?>
            <a title="Next" class="paginator-next" href="<?php echo $this->url(array(
                'page' => $this->next
            )) ?>">Next</a>
            <?php else : ?>
            <span class="paginator-next">Next</span>
            <?php endif ?>
        </li>
    </ul>
</div>
<?php endif ?>
